spring:
  application:
    name: learning-and-developement-service

  datasource:
    url: jdbc:postgresql://localhost:5432/LnD_services
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect